<a href="https://colab.research.google.com/github/gozdeydd/nlp_all/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

###Creating a tensor

In [4]:
print(torch.rand(5))

tensor([0.7506, 0.1012, 0.3359, 0.7313, 0.2522])


In [5]:
tsnr = torch.Tensor([[[3,2],[1,5]],[[6,4],[9,6]],[[2,4],[0,5]]])

In [6]:
tsnr

tensor([[[3., 2.],
         [1., 5.]],

        [[6., 4.],
         [9., 6.]],

        [[2., 4.],
         [0., 5.]]])

In [7]:
tsnr.device

device(type='cpu')

In [8]:
tsnr.shape # ilk rakam kac element var sonraki iki elementler nasil. burda 2X2 3 element var

torch.Size([3, 2, 2])

In [9]:
tsnr[1]

tensor([[6., 4.],
        [9., 6.]])

In [10]:
torch.ones_like(tsnr)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [11]:
torch.zeros_like(tsnr)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [12]:
torch.randn_like(tsnr)

tensor([[[-1.8117, -0.5723],
         [ 0.7751,  0.8491]],

        [[ 1.0118,  0.6157],
         [ 1.5587, -0.5982]],

        [[ 1.8408, -0.3428],
         [-0.0825, -0.6318]]])

In [13]:
import torch.nn as nn

In [14]:
linear = nn.Linear(10,2)
input = torch.randn(3,10)
output = linear(input)
output

tensor([[ 1.2594,  0.4294],
        [ 0.6250,  1.1788],
        [-0.4493,  0.8340]], grad_fn=<AddmmBackward0>)

In [15]:
relu = nn.ReLU() #creating a relu object
relu_output =relu(output)
relu_output

tensor([[1.2594, 0.4294],
        [0.6250, 1.1788],
        [0.0000, 0.8340]], grad_fn=<ReluBackward0>)

###Optimizers in pytorch

In [16]:
import torch.optim as optim

In [17]:
mlp_laye = nn.Sequential(nn.Linear(5,2), nn.BatchNorm1d(2),nn.ReLU())
mlp_laye

Sequential(
  (0): Linear(in_features=5, out_features=2, bias=True)
  (1): BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
)

In [18]:
#trying this nn
input = torch.randn(5,5) + 1
input

tensor([[ 0.1186,  2.9115,  0.0135,  1.3685,  0.9707],
        [ 2.4184,  1.0748,  0.3752,  0.8036,  1.3941],
        [ 1.9864, -0.3987,  0.2418,  0.4000,  0.6596],
        [ 0.6670,  1.7851,  1.5104,  0.5331,  1.1859],
        [-0.1917, -1.5268,  1.5374,  0.6736,  0.9955]])

In [19]:
mlp_laye(input)

tensor([[0.0000, 1.3793],
        [0.5466, 0.0000],
        [0.8324, 0.0000],
        [0.0000, 0.8862],
        [0.6087, 0.0000]], grad_fn=<ReluBackward0>)

In [20]:
adam_opt = optim.Adam(mlp_laye.parameters(), lr= 1e-1)
adam_opt

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    weight_decay: 0
)

In [22]:
train_ex = torch.randn(100,5) + 1
adam_opt.zero_grad()
curr_loss = torch.abs(1-mlp_laye(train_ex)).mean()
curr_loss.backward()

In [23]:
adam_opt.step()
print(curr_loss)

tensor(0.7451, grad_fn=<MeanBackward0>)
